# Generated by Django 5.1 on 2024-12-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0002_directionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionhistory',
            name='result1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='directionhistory',
            name='result2',
            field=models.TextField(default=''),
        ),
    ]
