# Generated by Django 5.1 on 2024-12-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0003_directionhistory_result1_directionhistory_result2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionhistory',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='directionhistory',
            name='result2',
        ),
    ]
