# Generated by Django 5.1 on 2024-12-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0007_remove_userprofile_username_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
