# Generated by Django 5.1 on 2024-12-22 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0012_remove_like_profile_remove_like_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bad_reviews',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='good_reviews',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_reviews', models.IntegerField(default=0)),
                ('bad_reviews', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
