# Generated by Django 5.1 on 2024-12-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0013_remove_comment_bad_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bad_reviews',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='good_reviews',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Capstone.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='review_type',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=10),
            preserve_default=False,
        ),
    ]
