# Generated by Django 5.1 on 2024-12-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0014_remove_profile_bad_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review_type',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=10),
        ),
    ]
