# Generated by Django 5.1 on 2024-12-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0016_searchhistory_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='coordinates',
        ),
    ]
