# Generated by Django 5.1 on 2024-12-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone', '0017_remove_searchhistory_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
    ]
