# Generated by Django 5.1 on 2024-09-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listings_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronic'), ('TY', 'Toys'), ('ARM', 'Armour'), ('WEAP', 'Weapons'), ('Body Powered Devices', 'Body Powered Devices')], max_length=100),
        ),
    ]
