# Generated by Django 5.1 on 2024-09-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Toys', 'Toys'), ('Armour', 'Armour'), ('Weapons', 'Weapons'), ('Body Powered Devices', 'Body Powered Devices')], max_length=100),
        ),
    ]
