# Generated by Django 5.1 on 2024-09-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_listings_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='starting_bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
