# Generated by Django 5.1 on 2024-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_listings_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
