# Generated by Django 5.1 on 2024-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_listings_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
