# Generated by Django 5.1 on 2024-09-29 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_listings_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
