# Generated by Django 5.1 on 2024-09-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_listings_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='starting_bid',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
