# Generated by Django 5.1 on 2024-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_comments_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
