# Generated by Django 5.1 on 2024-09-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auction_listings_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
