# Generated by Django 5.1 on 2024-10-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='slug',
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
