# Generated by Django 5.1 on 2024-10-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_bidding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='seller',
            new_name='bidder',
        ),
    ]
