# Generated by Django 5.1 on 2024-10-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_bid_delete_bidding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='place_bid',
            new_name='bid_amount',
        ),
    ]
