# Generated by Django 5.1 on 2024-10-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_rename_place_bid_bid_bid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction_listings'),
        ),
    ]
