# Generated by Django 5.1 on 2024-10-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_rename_bid_amount_bid_amount_rename_bidder_bid_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Toys', 'Toys'), ('Armor', 'Armor'), ('Weapons', 'Weapons'), ('Body Powered Devices', 'Body Powered Devices'), ('Treasure', 'Treasure')], max_length=100),
        ),
    ]
