# Generated by Django 5.1 on 2024-10-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_comments_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auction_listings',
            new_name='auction_listing',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
