# Generated by Django 5.1 on 2024-10-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_rename_auction_listings_auction_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
