# Generated by Django 5.1 on 2024-10-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('No Category', 'No Category'), ('Toys', 'Toys'), ('Armor', 'Armor'), ('Weapons', 'Weapons'), ('Body Powered Devices', 'Body Powered Devices'), ('Treasure', 'Treasure')], max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
    ]
